config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :tasks do
    collection do
      get "unclosed"
    end
    member do
      patch "done"
    end
  end

  root "pages#index"
  get "about", :to => "pages#about", :as => "about"
  get "place", :to => "pages#place", :as => "place"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name,  :presence => true,  :uniqueness => true
  validates :status,  :inclusion => [true,false]
  validates :deadline,  :presence => true

  scope :closed,  lambda {where(:status => true)}
  scope :unclosed,  lambda {where.not(:status => true)}
  scope :recently,  lambda {where("deadline <= ?",3.days.since)}
  scope :search,  lambda{|name| where("name like ?","%#{name}%") if name.present?}
end

app/models/user.rb
class User < ApplicationRecord
  before_create :encrypted_password

  validates :name,  :presence => true
  validates :email,  :presence => true,:uniqueness => true

  private
  def encrypted_password
    self.password = Digest::SHA1.hexdigest(self.password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def about
  end
  def place
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, :only => [:show, :edit, :update, :destroy, :done]

  def unclosed
    @tasks = Task.unclosed
    render :action => "index"
  end

  def done
    # render :plain => "doneです"
    @task.update(:status => true)
    redirect_to tasks_path
  end

  def index
    @name = params[:name]
    @tasks = Task.search(@name)
  end

  def show
    # render :plain => "task controllerのshow actionです"
  end

  def new
    @task = Task.new(:status => false)
  end

  def edit
    # render :plain => "editです"
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task),:notice => "タスクを登録しました。"
    else
      render :action => "new"
    end
  end

  def update
    if @task.update(task_params)
      redirect_to task_path(@task),:notice => "タスクを更新しました。"
    else
      render :action => "edit"
    end
  end

  def destroy
  @task.destroy
  redirect_to tasks_path, :alert => "タスクを削除しました。"
  end


  private
  def task_params
    params.require(:task).permit(:name,:deadline,:status)
  end

  def find_task
    @task =Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :birthday)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def humanize_date(date)
    date.strftime("%Y年%m月%d日")
  end

  def humanize_status(status)
    status ? "完了" : "未完了"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div id="header">
  <%= link_to "ユーザ一覧",users_path %> |
  <%= link_to "ホーム",root_path %> |
  <%= link_to "このサイトについて",about_path %> |
  <%= link_to "練習用",place_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= stylesheet_link_tag    'application', :media => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id='container'>
      <%= render "layouts/header" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>このサイトについて</h1>
<p>ToDoは認証とタグ付け機能を持ったリスト管理アプリケーションです。</p>

app/views/pages/index.html.erb
<h1>ToDoアプリケーションへようこそ</h1>

app/views/pages/place.html.erb
<h1>練習用</h1>
<p>このページはRailsのビュー昨日の練習用に使用してください。</p>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %> errors.</h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status,"ステータス" %><br />
    <%= f.radio_button :status,true %> 完了
    <%= f.radio_button :status,false %> 未完了
  </div>
  <div class="field">
    <%= f.label :name,"名前" %><br />
    <%= f.text_field :name %><br />
  </div>
  <div class="field">
    <%= f.label :deadline,"締め切り" %><br />
    <%= f.date_select :deadline, use_month_numbers: true %><br />
  </div>
  <%= f.submit "登録" %>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

<%= render "form"%>
<%= link_to "タスク一覧に戻る",tasks_path%>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<p><%= link_to  "新規作成",new_task_path %></p>
<p><%= link_to  "未完了タスク一覧",unclosed_tasks_path %></p>

<%= form_tag tasks_path,method: :get do %>
  <%= text_field_tag :name, @name %>
  <%= submit_tag "検索"%>
<% end %>
<table>
  <tr>
    <th>状態</th>
    <th>タスク名</th>
    <th>締め切り</th>
    <th></th>
  </tr>
<% @tasks.each do |task| %>
  <tr>
    <td><%= humanize_status(task.status) %></td>
    <td><%= task.name %></td>
    <td><%= humanize_date(task.deadline) %></td>
    <td>
      <%= link_to  "表示", task_path(task) %> |
      <%= link_to  "編集", edit_task_path(task) %> |
      <%= link_to  "削除", task_path(task), method: :delete, data: {confirm:  "本当に削除しますか？"} %> |
      <%= link_to  "完了", done_task_path(task), method: :patch %>
    </td>
  </tr>
<% end %>
</table>

app/views/tasks/new.html.erb
<h1>タスク作成</h1>
<%= render "form"%>
<%= link_to "タスク一覧に戻る",tasks_path%>

app/views/tasks/show.html.erb
<h1>タスク一覧</h1>
<div id="notice"><%= notice %></div>

<table>
  <tr>
    <th>状態</th>
    <td><%= humanize_status(@task.status) %></td><br>
  </tr>
  <tr>
    <th>タスク名</th>
    <td><%= @task.name %></td>
  </tr>
  <tr>
    <th>締め切り</th>
    <td><%=humanize_date(@task.deadline)%></td>
  </tr>
</table>

<p>
  <%= link_to "編集",edit_task_path(@task) %>
  <%= link_to "戻る",tasks_path(@task) %>
</p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select  :birthday,
                          id: :user_birthday,
                          :start_year => 1940,
                          :end_year => Date.today.year,
                          :use_month_numbers => true %>
  </div>
  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :password %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <!-- <td><%= user.birthday %></td> -->
        <td><%= humanize_date(user.birthday) %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= humanize_date(@user.birthday) %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>